### PR TITLE
fix: Allow spaces in `javaagent` path

### LINKED ISSUE #25: Surefire errors out when the AppMap JAR path contains a space
Wrap the `javaagent` argument in quotes.
 
https://github.com/applandinc/appmap-maven-plugin/blob/master/src/main/java/com/appland/appmap/maven/LoadJavaAppMapAgentMojo.java#L99

### PR DESCRIPTION
**Pull request by dustinbyrne**
This change wraps the `javaagent` arg line in quotes, in case the path contains spaces.

Resolves #25

### CODE REVIEW

File: src/main/java/com/appland/appmap/maven/LoadJavaAppMapAgentMojo.java [hunk 1]
```diff
@@ -83,21 +83,23 @@ private String buildArguments() {
         return builder.toString();
     }
 
+    private String javaAgentArgLine() {
+        return format("\"-javaagent:%s\"", StringEscapeUtils.escapeJava(getAppMapAgentJarPath()));
```
Comment (apotterri) [inline src/main/java/com/appland/appmap/maven/LoadJavaAppMapAgentMojo.java:87]: Have you tested this change on Windows? Does getAppMapAgentJarPath return paths with backslashes? If so, does StringEscapeUtils.escapeJava do what want?

Comment (apotterri) [reply src/main/java/com/appland/appmap/maven/LoadJavaAppMapAgentMojo.java:87]: I tested this on Windows. Seems to work properly.

**Review by apotterri — APPROVED** [review]
LGTM, works on Windows.
